[package]
name = "stalagmite-poly"
version = "0.1.0"
edition = "2024"

[dependencies]
malachite = "0.6.1"
stalagmite-base = { path = "../stalagmite-base" }

[[test]]
name = "lib"
path = "test/lib.rs"
