[workspace]
resolver = "3"
members = ["stalagmite", "stalagmite-base", "stalagmite-bench", "stalagmite-fq", "stalagmite-lat", "stalagmite-mat", "stalagmite-mpoly", "stalagmite-nf", "stalagmite-poly", "stalagmite-qp", "stalagmite-vec", "stalagmite-zn"]
