[package]
name = "stalagmite-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
stalagmite-poly = { path = "../stalagmite-poly" }
stalagmite-poly2 = { path = "../stalagmite-poly2" }
malachite = "0.4.0"

[[bench]]
name = "intpoly_sum"
harness = false
